## <font color='darkblue'>Tensor</font>
<b><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor</a></b> 是 PyTorch 中重要的資料結構, 可被視為是一個高維陣列. 它可以是一個數 (純量), 一維陣列 (向量), 二維陣列 (矩陣) 或更高維陣列. Tensor 和 numpy 的 ndarrays 類似, 但 Tensor 可以使用 GPU 加速. Tensor 的使用和 numpy 及 MATLAB 的介面十分相似, 透過下面幾個範例可以了解 Tensor 的基本使用方法:

In [28]:
import torch as t

x1 = t.Tensor(5, 3)  # 建構 5x3 矩陣, 只分配空間並未初始化
print('x1:\n{}\n'.format(x1))

x2 = t.zeros(5, 3, dtype=t.double) # 建構 5x3 矩陣, 並初始化為 0
print('x2:\n{}\n'.format(x2))

x3 = t.Tensor([[1,2,3],[4,5,6],[7,8,9]])  # 直接從資料建構 3x3 矩陣
print('x3:\n{}\n'.format(x3))

# create a tensor based on an existing tensor. 
# These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x4 = x2.new_ones(5, 3)
print('x4:\n{}\n'.format(x4))

x5 = t.randn_like(x4, dtype=t.float)    # override dtype!
print('x5:\n{}\n'.format(x5))

x1:
tensor([[7.0721e+31, 7.3773e+28, 1.0901e+27],
        [7.1345e+31, 7.2128e+22, 4.8203e+30],
        [3.3219e+12, 3.7870e+12, 9.1776e+02],
        [2.8573e+32, 3.2181e+21, 2.7130e-09],
        [3.9567e-14, 7.3706e+28, 4.1576e+21]])

x2:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

x3:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

x4:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

x5:
tensor([[-1.0447, -1.4295, -2.2646],
        [-1.3875, -0.9201, -0.8934],
        [-0.5727,  0.6177, -0.2524],
        [-0.9369, -0.5688,  0.5641],
        [ 1.8066, -0.7115, -0.5504]])



In [3]:
# 使用 [0,1] 均勻分布隨機初始化 x 陣列
x = t.rand(5, 3)
x

tensor([[0.0322, 0.3882, 0.4314],
        [0.3406, 0.9019, 0.8997],
        [0.4141, 0.3662, 0.3030],
        [0.4531, 0.8691, 0.7999],
        [0.2298, 0.6488, 0.2531]])

In [5]:
# 查看 x 的維度
print(x.size())

# 兩種存取 x 的 column 數目
print("x.column = {} or {}".format(x.size()[1], x.size(1)))

torch.Size([5, 3])
x.column = 3 or 3


torch.Size 是 tuple 物件的子類別, 它支援 tuple 的所有操作.

In [8]:
print("x.Size is tupel? {}".format(isinstance(x.size(), tuple)))

x.Size is tupel? True


接著來看 tensor 的幾種簡單數學操作.

In [11]:
y = t.rand(5, 3)
print("y:\n{}".format(y))

# 加法的第一種寫法
x + y 

y:
tensor([[0.4779, 0.6267, 0.0901],
        [0.8913, 0.7919, 0.5582],
        [0.7278, 0.2964, 0.2430],
        [0.2231, 0.9145, 0.1500],
        [0.9088, 0.2084, 0.9089]])


tensor([[0.5100, 1.0149, 0.5216],
        [1.2318, 1.6938, 1.4579],
        [1.1419, 0.6626, 0.5460],
        [0.6761, 1.7836, 0.9500],
        [1.1386, 0.8572, 1.1619]])

In [12]:
# 加法的第二種寫法
t.add(x, y)

tensor([[0.5100, 1.0149, 0.5216],
        [1.2318, 1.6938, 1.4579],
        [1.1419, 0.6626, 0.5460],
        [0.6761, 1.7836, 0.9500],
        [1.1386, 0.8572, 1.1619]])

In [13]:
# 加法的第三種寫法: 指定結果的輸出目標為 result
result = t.Tensor(5, 3)  # 分配空間
t.add(x, y, out=result)  # 輸出到 result
result

tensor([[0.5100, 1.0149, 0.5216],
        [1.2318, 1.6938, 1.4579],
        [1.1419, 0.6626, 0.5460],
        [0.6761, 1.7836, 0.9500],
        [1.1386, 0.8572, 1.1619]])

In [14]:
print("Original y:\n{}\n".format(y))

# 第一種加法不改變 y 的內容
y.add(x)  # 普通加法, 不改變 y 內容
print("y.add(x) got y:\n{}\n".format(y))

# 第二種加法會改變 y 的內容
y.add_(x)  # inplace 加法, 改變 y 內容
print("y.add_(x) got y:\n{}\n".format(y))

Original y:
tensor([[0.4779, 0.6267, 0.0901],
        [0.8913, 0.7919, 0.5582],
        [0.7278, 0.2964, 0.2430],
        [0.2231, 0.9145, 0.1500],
        [0.9088, 0.2084, 0.9089]])

y.add(x) got y:
tensor([[0.4779, 0.6267, 0.0901],
        [0.8913, 0.7919, 0.5582],
        [0.7278, 0.2964, 0.2430],
        [0.2231, 0.9145, 0.1500],
        [0.9088, 0.2084, 0.9089]])

y.add_(x) got y:
tensor([[0.5100, 1.0149, 0.5216],
        [1.2318, 1.6938, 1.4579],
        [1.1419, 0.6626, 0.5460],
        [0.6761, 1.7836, 0.9500],
        [1.1386, 0.8572, 1.1619]])



<b><font color='darkred'>注意:</font></b> 函數名稱後面帶底線的操作會修改 Tensor 本身.

## <font color='darkblue'>Supplement </font>
* <a href='https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py'>PyTorch Tutorials >  Deep Learning with PyTorch: A 60 Minute Blitz > What is PyTorch?</a>